/**
 * Private key export/import helpers for the browser vault.
 *
 * Formats supported (matching common GnuPG interchange):
 *   - ASCII-armored .asc  — `gpg --import key.asc` (stable cross-version format)
 *   - Binary .gpg         — same packets, no armor
 *   - QR code (SVG)       — armored key as a scannable code (fits ECC keys)
 *   - Paper backup (HTML) — printable page: armored text + QR + import instructions
 *
 * Exports are ALWAYS OpenPGP passphrase-protected (like gpg --export-secret-keys,
 * which keeps the S2K encryption at rest). Keys stored with device or passkey
 * protection are not OpenPGP-locked, so a passphrase must be applied at export
 * time via ensurePassphraseProtected().
 */

import { encryptKey, readPrivateKey } from "openpgp";
import { qrSvg } from "./qr.js";

/**
 * Whether the armored private key is OpenPGP passphrase-locked.
 * @param {string} armored
 * @returns {Promise<boolean>}
 */
export async function isArmoredKeyLocked(armored) {
  const key = await readPrivateKey({ armoredKey: armored });
  return !key.isDecrypted();
}

/**
 * Return an armored key that is guaranteed to be passphrase-locked.
 * If the key is already locked, it is returned unchanged (the passphrase
 * argument is ignored). If unlocked, it is locked with `passphrase`.
 *
 * @param {string} armored
 * @param {string} [passphrase]
 * @returns {Promise<string>}
 */
export async function ensurePassphraseProtected(armored, passphrase) {
  const key = await readPrivateKey({ armoredKey: armored });
  if (!key.isDecrypted()) return armored;
  if (!passphrase) {
    throw new Error(
      "This key is not passphrase-protected. Set an export passphrase first."
    );
  }
  const locked = await encryptKey({ privateKey: key, passphrase });
  return locked.armor();
}

/**
 * Convert an armored private key to binary OpenPGP format (.gpg).
 * The key's at-rest passphrase protection is preserved.
 * @param {string} armored
 * @returns {Promise<Uint8Array>}
 */
export async function armoredToBinary(armored) {
  const key = await readPrivateKey({ armoredKey: armored });
  return key.write();
}

/**
 * Render an armored key as a QR code SVG.
 * A Curve25519 private key (~900 armored chars) fits comfortably; large RSA
 * keys may exceed QR capacity (2953 bytes) and will throw.
 * @param {string} armored
 * @returns {string} SVG markup
 */
export function armoredToQrSvg(armored) {
  try {
    return qrSvg(armored, { ecl: "L", moduleSize: 3, margin: 4 });
  } catch (err) {
    throw new Error(
      "Key too large for a single QR code (RSA keys usually are — use the .asc file instead)."
    );
  }
}

/**
 * Build a printable paper-backup HTML document.
 * Downloaded as a file the user opens locally and prints — avoids CSP
 * restrictions on injected inline styles in the app origin.
 *
 * @param {object} opts
 * @param {string} opts.armored  passphrase-locked armored private key
 * @param {string} opts.fingerprint
 * @param {string} opts.uid
 * @param {string|null} [opts.expires]
 * @returns {string} full HTML document
 */
export function paperBackupHtml({ armored, fingerprint, uid, expires }) {
  let qrBlock = "";
  try {
    qrBlock = `<div class="qr">${armoredToQrSvg(armored)}</div>`;
  } catch (_) {
    qrBlock = "<p><em>Key too large for QR — restore from the text below.</em></p>";
  }
  const esc = (s) =>
    String(s || "").replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
  const fprSpaced = String(fingerprint || "")
    .replace(/(.{4})/g, "$1 ")
    .trim();
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PGP key paper backup — ${esc(fingerprint)}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; color: #111; }
  h1 { font-size: 1.3rem; }
  .meta { font-size: 0.9rem; margin: 0.75rem 0; }
  .meta code { background: #f2f2f2; padding: 0.1rem 0.3rem; }
  pre { font-size: 0.62rem; line-height: 1.35; white-space: pre-wrap; word-break: break-all;
        border: 1px solid #ccc; padding: 0.75rem; }
  .qr { margin: 1rem 0; }
  .qr svg { width: 260px; height: 260px; }
  .warn { border: 2px solid #b00; padding: 0.6rem 0.8rem; font-size: 0.85rem; margin: 1rem 0; }
  .steps { font-size: 0.85rem; }
  @media print { .noprint { display: none; } }
</style>
</head>
<body>
  <h1>OpenPGP private key — paper backup</h1>
  <p class="meta">
    UID: <code>${esc(uid)}</code><br>
    Fingerprint: <code>${esc(fprSpaced)}</code><br>
    ${expires ? `Key expires: <code>${esc(expires)}</code><br>` : ""}
    Generated by Basilisk on ${new Date().toISOString().slice(0, 10)}
  </p>
  <div class="warn">
    This page contains your PRIVATE key (passphrase-protected).
    Store it like cash: safe, fireproof box, or safe-deposit box.
    Anyone with this page AND your passphrase can read your messages.
  </div>
  ${qrBlock}
  <pre>${esc(armored)}</pre>
  <div class="steps">
    <strong>Restore with GnuPG:</strong>
    <ol>
      <li>Scan the QR code, or type/OCR the text block into a file <code>key.asc</code></li>
      <li>Run <code>gpg --import key.asc</code></li>
      <li>Enter your passphrase when prompted for use</li>
    </ol>
  </div>
  <p class="noprint"><button onclick="window.print()">Print this page</button></p>
</body>
</html>`;
}

/**
 * Trigger a browser download.
 * @param {string} filename
 * @param {string|Uint8Array} data
 * @param {string} mime
 */
export function downloadFile(filename, data, mime) {
  const blob = new Blob([data], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

/**
 * Parse an imported armored private key: fingerprint, primary UID, locked state.
 * @param {string} armored
 * @returns {Promise<{ fingerprint: string, uid: string, email: string, locked: boolean, expires: string|null }>}
 */
export async function inspectPrivateKey(armored) {
  const key = await readPrivateKey({ armoredKey: armored });
  const fingerprint = key.getFingerprint().toUpperCase();
  let uid = "";
  let email = "";
  try {
    const primary = await key.getPrimaryUser();
    uid = primary?.user?.userID?.userID || "";
    email = primary?.user?.userID?.email || "";
  } catch (_) {
    const users = key.users || [];
    uid = users[0]?.userID?.userID || "";
    email = users[0]?.userID?.email || "";
  }
  let expires = null;
  try {
    const exp = await key.getExpirationTime();
    if (exp instanceof Date) expires = exp.toISOString();
  } catch (_) {
    expires = null;
  }
  return { fingerprint, uid, email, locked: !key.isDecrypted(), expires };
}
