/**
 * Build toolkit glyph module + docs from exported SVG assets.
 *
 * Source of truth:
 *   web/glyphs/manifest.json  — ids, groups, metaphors, descriptions
 *   web/glyphs/svg/<id>.svg   — viewBox 0 0 20 20 stroke icons
 *
 * Outputs:
 *   web/src/lib/toolkit/glyphs.js  — GLYPH_PATHS + glyphHtml()
 *   docs/GLYPHS.md                 — human catalog
 *
 * Usage: node scripts/build-glyphs.mjs
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  mkdirSync,
  existsSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = resolve(__dirname, "..");
const REPO_ROOT = resolve(WEB_ROOT, "..");
const GLYPHS_DIR = join(WEB_ROOT, "glyphs");
const SVG_DIR = join(GLYPHS_DIR, "svg");
const MANIFEST_PATH = join(GLYPHS_DIR, "manifest.json");
const OUT_JS = join(WEB_ROOT, "src", "lib", "toolkit", "glyphs.js");
const OUT_DOC = join(REPO_ROOT, "docs", "GLYPHS.md");

const GROUP_LABELS = {
  toolbox: "Toolboxes",
  shelf: "Shelves",
  ui: "Toolbar / kernel",
  keyring: "Keyring actions",
};

/**
 * @param {string} svg
 * @returns {string}
 */
function extractInner(svg) {
  const match = svg.match(/<svg\b[^>]*>([\s\S]*)<\/svg\s*>/i);
  if (!match) {
    throw new Error("SVG missing root <svg>…</svg>");
  }
  return match[1]
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * @param {string} s
 * @returns {string}
 */
function jsString(s) {
  return JSON.stringify(s);
}

function loadManifest() {
  if (!existsSync(MANIFEST_PATH)) {
    throw new Error(`Missing glyph manifest: ${MANIFEST_PATH}`);
  }
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  if (!Array.isArray(manifest.glyphs) || !manifest.glyphs.length) {
    throw new Error("manifest.glyphs must be a non-empty array");
  }
  return manifest;
}

/** @param {{ glyphs: { id: string }[] }} manifest */
function buildGlyphPaths(manifest) {
  /** @type {Record<string, string>} */
  const paths = {};
  const svgFiles = new Set(
    existsSync(SVG_DIR)
      ? readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg"))
      : []
  );

  for (const g of manifest.glyphs) {
    const id = String(g.id || "").trim();
    if (!id) throw new Error("glyph entry missing id");
    const file = `${id}.svg`;
    const abs = join(SVG_DIR, file);
    if (!existsSync(abs)) {
      throw new Error(`Missing SVG asset for glyph "${id}": ${abs}`);
    }
    svgFiles.delete(file);
    const inner = extractInner(readFileSync(abs, "utf8"));
    if (!inner) throw new Error(`Empty SVG inner markup: ${file}`);
    if (paths[id]) throw new Error(`Duplicate glyph id: ${id}`);
    paths[id] = inner;
  }

  if (svgFiles.size) {
    const orphans = [...svgFiles].sort().join(", ");
    throw new Error(`SVG assets not listed in manifest: ${orphans}`);
  }

  return paths;
}

/**
 * @param {Record<string, string>} paths
 */
function emitGlyphsJs(paths) {
  const keys = Object.keys(paths).sort((a, b) => a.localeCompare(b));
  const entries = keys
    .map((id) => `  ${jsString(id)}: ${jsString(paths[id])},`)
    .join("\n");

  return `/**
 * AUTO-GENERATED by scripts/build-glyphs.mjs — do not edit.
 * Source: web/glyphs/manifest.json + web/glyphs/svg/*.svg
 * Docs: docs/GLYPHS.md
 *
 * Inline stroke SVG fragments for toolkit toolbox / shelf glyphs.
 * viewBox 0 0 20 20 — matches landing-page feature-icon language.
 */

/** @type {Record<string, string>} */
export const GLYPH_PATHS = {
${entries}
};

/**
 * @param {string|undefined|null} id
 * @param {string} [className]
 * @returns {string}
 */
export function glyphHtml(id, className = "ops-glyph") {
  const key = String(id || "");
  const inner = GLYPH_PATHS[key];
  if (!inner) return "";
  return \`<svg class="\${className}" width="16" height="16" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">\${inner}</svg>\`;
}
`;
}

/**
 * @param {*} manifest
 */
function emitDocs(manifest) {
  const byGroup = new Map();
  for (const g of manifest.glyphs) {
    const group = g.group || "other";
    if (!byGroup.has(group)) byGroup.set(group, []);
    byGroup.get(group).push(g);
  }

  const groupOrder = ["toolbox", "shelf", "ui", "keyring"];
  const groups = [
    ...groupOrder.filter((k) => byGroup.has(k)),
    ...[...byGroup.keys()].filter((k) => !groupOrder.includes(k)).sort(),
  ];

  let body = `# Toolkit glyphs

Stroke SVG icons for the ops drawer (toolboxes, shelves) and toolkit chrome.
Assets live under \`web/glyphs/\`; \`web/src/lib/toolkit/glyphs.js\` is **generated
at build time** by \`npm run glyphs\` (\`scripts/build-glyphs.mjs\`).

| | |
|---|---|
| Manifest | \`web/glyphs/manifest.json\` |
| SVG assets | \`web/glyphs/svg/<id>.svg\` |
| Generated module | \`web/src/lib/toolkit/glyphs.js\` |
| View box | \`${manifest.viewBox || "0 0 20 20"}\` |
| Stroke | \`currentColor\`, width \`${manifest.strokeWidth ?? 1.6}\`, round caps/joins |

**Conventions:** single-color line icons, recognizable without a caption where
possible. Prefer established crypto UI metaphors (ModernPGP locked envelope,
FIDO passkey person+key, Shamir share fragments) over abstract decoration.

Rebuild after editing an SVG or the manifest:

\`\`\`bash
cd web && npm run glyphs
\`\`\`

\`predev\` / \`prebuild\` / \`pretest\` run the same step automatically.

---

`;

  for (const group of groups) {
    const label = GROUP_LABELS[group] || group;
    body += `## ${label}\n\n`;
    body += `| Id | Label | Metaphor | Description |\n`;
    body += `|----|-------|----------|-------------|\n`;
    for (const g of byGroup.get(group)) {
      const refs =
        Array.isArray(g.refs) && g.refs.length
          ? ` <br><small>${g.refs.map((r) => escapeMd(String(r))).join("; ")}</small>`
          : "";
      body += `| \`${g.id}\` | ${escapeMd(g.label || g.id)} | ${escapeMd(g.metaphor || "—")} | ${escapeMd(g.description || "—")}${refs} |\n`;
    }
    body += "\n";
  }

  body += `## Asset format

Each \`web/glyphs/svg/<id>.svg\` is a complete icon:

\`\`\`svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none"
     stroke="currentColor" stroke-width="1.6"
     stroke-linecap="round" stroke-linejoin="round">
  <!-- geometry -->
</svg>
\`\`\`

The builder strips the root \`<svg>\` and embeds the inner markup into
\`GLYPH_PATHS[id]\`. Runtime \`glyphHtml(id)\` wraps that fragment with the
shared attributes used in the toolkit UI.

See also [CRYPTOGRAPHY.md](./CRYPTOGRAPHY.md) (toolbox taxonomy) and
\`registry.js\` \`TOOLBOX_META\` / \`SHELF_META\` \`glyph\` keys.
`;

  return body;
}

/** @param {string} s */
function escapeMd(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function main() {
  const manifest = loadManifest();
  const paths = buildGlyphPaths(manifest);

  mkdirSync(dirname(OUT_JS), { recursive: true });
  mkdirSync(dirname(OUT_DOC), { recursive: true });

  writeFileSync(OUT_JS, emitGlyphsJs(paths), "utf8");
  writeFileSync(OUT_DOC, emitDocs(manifest), "utf8");

  console.log(
    `glyphs: wrote ${Object.keys(paths).length} icons → ${OUT_JS}\n` +
      `glyphs: wrote catalog → ${OUT_DOC}`
  );
}

main();
