#!/usr/bin/env bash
# Print GitHub Actions secret values from Terraform outputs (run after terraform apply).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/cloudshell"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform not found"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found (install jq to format JSON output)"
  exit 1
fi

cd "$TF_DIR"

if [[ ! -f terraform.tfstate ]] && [[ ! -d .terraform ]]; then
  echo "No Terraform state in $TF_DIR — run deploy-terraform-cloudshell.sh first."
  exit 1
fi

SECRETS_JSON="$(terraform output -json github_actions_secrets 2>/dev/null || true)"
SETUP_JSON="$(terraform output -json github_actions_setup 2>/dev/null || true)"

if [[ -z "$SECRETS_JSON" || "$SECRETS_JSON" == "null" ]]; then
  echo "github_actions_secrets output not found. Re-run terraform apply."
  exit 1
fi

TOKEN="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_TOKEN_SECRET')"
SUB_ID="$(echo "$SECRETS_JSON" | jq -r '.AZURE_SUBSCRIPTION_ID')"
TENANT_ID="$(echo "$SECRETS_JSON" | jq -r '.AZURE_TENANT_ID')"
NAME_PREFIX="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_NAME_PREFIX')"
RG="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_RESOURCE_GROUP')"
FN="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_FUNCTION_APP_NAME')"
FD_URL="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_FRONT_DOOR_URL')"
STORAGE="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_STORAGE_ACCOUNT // empty')"
SP_CMD="$(echo "$SETUP_JSON" | jq -r '.azure_credentials_command')"
STATIC_URL="$(echo "$SETUP_JSON" | jq -r '.static_website_url // empty')"

cat <<EOF
# GitHub Actions secrets for Basilisk
# Settings → Secrets and variables → Actions → New repository secret

Required:
  AZURE_CREDENTIALS        JSON from Azure service principal (--sdk-auth)
  BASILISK_TOKEN_SECRET    (generated by Terraform — value below)

Optional (workflow can read from Terraform state instead):
  AZURE_SUBSCRIPTION_ID    $SUB_ID
  AZURE_TENANT_ID          $TENANT_ID
  BASILISK_NAME_PREFIX     $NAME_PREFIX
  BASILISK_RESOURCE_GROUP  $RG
  BASILISK_FUNCTION_APP_NAME  $FN
  BASILISK_FRONT_DOOR_URL  $FD_URL
  BASILISK_STORAGE_ACCOUNT $STORAGE

--- BASILISK_TOKEN_SECRET ---
$TOKEN

--- Create AZURE_CREDENTIALS (run locally, paste JSON into GitHub secret) ---
$SP_CMD

--- GitHub CLI (requires gh auth login) ---
gh secret set BASILISK_TOKEN_SECRET --body "$TOKEN"

After AZURE_CREDENTIALS is set, trigger deploy from Actions → deploy workflow.

Deployed endpoints:
  Front Door:       $FD_URL
  Static website:   ${STATIC_URL:-(run terraform output static_website_url)}
  Function:         $FN (resource group: $RG)
  Storage account:  $STORAGE
EOF
