<#
.SYNOPSIS
  Print GitHub Actions secret values from Terraform outputs (run after terraform apply).
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path $PSScriptRoot -Parent
$TfDir = Join-Path $RepoRoot "terraform\cloudshell"

if (-not (Get-Command terraform -ErrorAction SilentlyContinue)) {
    throw "terraform not found"
}

Push-Location $TfDir
try {
    $secretsJson = terraform output -json github_actions_secrets | ConvertFrom-Json
    $setupJson = terraform output -json github_actions_setup | ConvertFrom-Json
}
catch {
    throw "Run deploy-terraform-cloudshell.ps1 first. $_"
}
finally {
    Pop-Location
}

Write-Host ""
Write-Host "# GitHub Actions secrets for Basilisk" -ForegroundColor Cyan
Write-Host "# Settings -> Secrets and variables -> Actions -> New repository secret"
Write-Host ""
Write-Host "Required:"
Write-Host "  AZURE_CREDENTIALS        JSON from Azure service principal (--sdk-auth)"
Write-Host "  BASILISK_TOKEN_SECRET    (generated by Terraform — value below)"
Write-Host ""
Write-Host "Optional:"
Write-Host "  AZURE_SUBSCRIPTION_ID    $($secretsJson.AZURE_SUBSCRIPTION_ID)"
Write-Host "  AZURE_TENANT_ID          $($secretsJson.AZURE_TENANT_ID)"
Write-Host "  BASILISK_NAME_PREFIX     $($secretsJson.BASILISK_NAME_PREFIX)"
Write-Host "  BASILISK_RESOURCE_GROUP  $($secretsJson.BASILISK_RESOURCE_GROUP)"
Write-Host "  BASILISK_FUNCTION_APP_NAME  $($secretsJson.BASILISK_FUNCTION_APP_NAME)"
Write-Host "  BASILISK_FRONT_DOOR_URL  $($secretsJson.BASILISK_FRONT_DOOR_URL)"
Write-Host ""
Write-Host "--- BASILISK_TOKEN_SECRET ---" -ForegroundColor Yellow
Write-Host $secretsJson.BASILISK_TOKEN_SECRET
Write-Host ""
Write-Host "--- Create AZURE_CREDENTIALS ---" -ForegroundColor Yellow
Write-Host $setupJson.azure_credentials_command
Write-Host ""
Write-Host "--- GitHub CLI ---" -ForegroundColor Yellow
Write-Host "gh secret set BASILISK_TOKEN_SECRET --body `"$($secretsJson.BASILISK_TOKEN_SECRET)`""
Write-Host ""
Write-Host "Front Door: $($secretsJson.BASILISK_FRONT_DOOR_URL)"
