#!/usr/bin/env bash
# Print GitHub Actions secret values from Terraform outputs (run after terraform apply).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/cloudshell"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform not found"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found (install jq to format JSON output)"
  exit 1
fi

cd "$TF_DIR"

if ! terraform output -json github_actions_secrets >/dev/null 2>&1; then
  echo "No Terraform state / outputs in $TF_DIR — run deploy-terraform-cloudshell.sh or bootstrap-tfstate.sh first."
  exit 1
fi

SECRETS_JSON="$(terraform output -json github_actions_secrets 2>/dev/null || true)"
SETUP_JSON="$(terraform output -json github_actions_setup 2>/dev/null || true)"

if [[ -z "$SECRETS_JSON" || "$SECRETS_JSON" == "null" ]]; then
  echo "github_actions_secrets output not found. Re-run terraform apply."
  exit 1
fi

TOKEN="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_TOKEN_SECRET')"
SUB_ID="$(echo "$SECRETS_JSON" | jq -r '.AZURE_SUBSCRIPTION_ID')"
TENANT_ID="$(echo "$SECRETS_JSON" | jq -r '.AZURE_TENANT_ID')"
NAME_PREFIX="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_NAME_PREFIX')"
RG="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_RESOURCE_GROUP')"
FN="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_FUNCTION_APP_NAME')"
FD_URL="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_FRONT_DOOR_URL')"
PUBLIC_URL="$(terraform output -raw public_url 2>/dev/null || echo "$FD_URL")"
CUSTOM_DOMAIN="$(terraform output -raw custom_domain 2>/dev/null || true)"
STORAGE="$(echo "$SECRETS_JSON" | jq -r '.BASILISK_STORAGE_ACCOUNT // empty')"
SP_CMD="$(echo "$SETUP_JSON" | jq -r '.azure_credentials_command')"
STATIC_URL="$(echo "$SETUP_JSON" | jq -r '.static_website_url // empty')"
OAUTH_JSON="$(terraform output -json oauth_setup 2>/dev/null || echo '{}')"
GOOGLE_REDIRECT="$(echo "$OAUTH_JSON" | jq -r '.google_redirect_uri // empty')"
GOOGLE_REDIRECTS="$(echo "$OAUTH_JSON" | jq -r '.google_redirect_uris[]? // empty' 2>/dev/null || true)"
AAD_REDIRECT="$(echo "$OAUTH_JSON" | jq -r '.aad_redirect_uri // empty')"
AAD_REDIRECTS="$(echo "$OAUTH_JSON" | jq -r '.aad_redirect_uris[]? // empty' 2>/dev/null || true)"
FN_HOST="$(echo "$OAUTH_JSON" | jq -r '.function_app_hostname // empty')"
AUTH_DOMAIN="$(echo "$OAUTH_JSON" | jq -r '.google_authorized_domain // empty')"

cat <<EOF
# GitHub Actions secrets for Basilisk
# Settings → Secrets and variables → Actions → New repository secret

Required:
  AZURE_CREDENTIALS        JSON from Azure service principal (--sdk-auth)
  BASILISK_TOKEN_SECRET    (generated by Terraform — value below)

Optional (workflow can read from Terraform state instead):
  AZURE_SUBSCRIPTION_ID    $SUB_ID
  AZURE_TENANT_ID          $TENANT_ID
  BASILISK_NAME_PREFIX     $NAME_PREFIX
  BASILISK_RESOURCE_GROUP  $RG
  BASILISK_FUNCTION_APP_NAME  $FN
  BASILISK_FRONT_DOOR_URL  $PUBLIC_URL
  BASILISK_STORAGE_ACCOUNT $STORAGE

--- AWS (Route53 custom domain DNS) ---
Set repository secrets for deploy workflow:
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
IAM policy (minimum): route53:ChangeResourceRecordSets on hosted zone Z026512234X4JPOD7PZH1
Default Terraform: custom_domain=keys.b1tninja.com, route53_zone_id=Z026512234X4JPOD7PZH1

--- BASILISK_TOKEN_SECRET ---
$TOKEN

--- Create AZURE_CREDENTIALS (run locally, paste JSON into GitHub secret) ---
$SP_CMD

--- GitHub CLI (requires gh auth login) ---
gh secret set BASILISK_TOKEN_SECRET --body "$TOKEN"

After AZURE_CREDENTIALS is set, trigger deploy from Actions → deploy workflow.

Deployed endpoints:
  Public URL:       $PUBLIC_URL
  Front Door:       $(terraform output -raw front_door_url 2>/dev/null || echo "$FD_URL")
  Custom domain:    ${CUSTOM_DOMAIN:-(none)}
  Static website:   ${STATIC_URL:-(run terraform output static_website_url)}
  Function:         $FN (resource group: $RG)
  Storage account:  $STORAGE

--- OAuth / IdP setup (from terraform output oauth_setup) ---
Public URL:            ${PUBLIC_URL:-https://keys.b1tninja.com}
Function hostname:     ${FN_HOST:-$FN.azurewebsites.net}
Google redirect URIs (add ALL to Google Cloud OAuth client):
$(if [[ -n "$GOOGLE_REDIRECTS" ]]; then echo "$GOOGLE_REDIRECTS" | sed 's/^/  /'; else echo "  ${GOOGLE_REDIRECT:-https://${FN}.azurewebsites.net/.auth/login/google/callback}"; echo "  https://keys.b1tninja.com/.auth/login/google/callback"; fi)
  → Google Cloud → Credentials → OAuth client → Authorized redirect URIs
Entra redirect URIs (add ALL to App Registration):
$(if [[ -n "$AAD_REDIRECTS" ]]; then echo "$AAD_REDIRECTS" | sed 's/^/  /'; else echo "  ${AAD_REDIRECT:-https://${FN}.azurewebsites.net/.auth/login/aad/callback}"; fi)
  → Entra → App registrations → Authentication → Redirect URI (Web)

Google consent screen Authorized domains:
  Do NOT add azurewebsites.net (Microsoft owns it).
  Add the root domain you own (e.g. b1tninja.com) when using a custom domain.
$(if [[ -n "$AUTH_DOMAIN" && "$AUTH_DOMAIN" != "null" ]]; then echo "  Configured: $AUTH_DOMAIN (must verify in Search Console)"; else echo "  Optional: set TF_VAR_oauth_authorized_domain=b1tninja.com"; fi)

Full JSON: cd terraform/cloudshell && terraform output -json oauth_setup
EOF
