/**
 * Glyph asset catalog stays in sync with the generated module.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { GLYPH_PATHS, glyphHtml } from "../lib/toolkit/glyphs.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WEB_ROOT = resolve(__dirname, "../..");
const MANIFEST_PATH = join(WEB_ROOT, "glyphs", "manifest.json");
const SVG_DIR = join(WEB_ROOT, "glyphs", "svg");

describe("glyph assets", () => {
  it("has a manifest and matching SVG exports for every generated path", () => {
    expect(existsSync(MANIFEST_PATH)).toBe(true);
    const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
    const ids = manifest.glyphs.map((g) => g.id).sort();
    const pathIds = Object.keys(GLYPH_PATHS).sort();
    expect(pathIds).toEqual(ids);

    for (const g of manifest.glyphs) {
      expect(g.label, g.id).toBeTruthy();
      expect(g.metaphor, g.id).toBeTruthy();
      expect(g.description, g.id).toBeTruthy();
      expect(g.group, g.id).toBeTruthy();
      expect(existsSync(join(SVG_DIR, `${g.id}.svg`)), g.id).toBe(true);
      expect(GLYPH_PATHS[g.id].length).toBeGreaterThan(0);
      expect(glyphHtml(g.id)).toContain("<svg");
    }

    const svgFiles = readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg"));
    expect(svgFiles.sort()).toEqual(ids.map((id) => `${id}.svg`));
  });

  it("marks glyphs.js as generated", () => {
    const src = readFileSync(
      join(WEB_ROOT, "src", "lib", "toolkit", "glyphs.js"),
      "utf8"
    );
    expect(src).toMatch(/AUTO-GENERATED by scripts\/build-glyphs\.mjs/);
  });
});
