/**
 * AUTO-GENERATED by scripts/build-glyphs.mjs — do not edit.
 * Source: web/glyphs/manifest.json + web/glyphs/svg/*.svg
 * Docs: docs/GLYPHS.md
 *
 * Inline stroke SVG fragments for toolkit toolbox / shelf glyphs.
 * viewBox 0 0 20 20 — matches landing-page feature-icon language.
 */

/** @type {Record<string, string>} */
export const GLYPH_PATHS = {
  "aead": "<path d=\"M10 3l7 3v5c0 4-3 6.5-7 8-4-1.5-7-4-7-8V6l7-3z\"/>",
  "agent": "<path d=\"M7.5 10.5a2.5 2.5 0 112.7-2.4L14 12v1.5h-1.5V15H11v-1.5H9.8z\"/><circle cx=\"7.2\" cy=\"8\" r=\"0.9\"/><path d=\"M14.5 4.5a5.5 5.5 0 11-9 0\"/><path d=\"M14.5 4.5V7H12\"/>",
  "agreement": "<circle cx=\"5\" cy=\"9\" r=\"2.4\"/><path d=\"M7.2 9H9.5\"/><circle cx=\"15\" cy=\"11\" r=\"2.4\"/><path d=\"M12.8 11H10.5\"/><path d=\"M9.5 7.5v5M10.5 7.5v5\"/>",
  "attestation": "<path d=\"M10 2l7 3v5c0 3.5-2.5 6-7 7.5C5.5 16 3 13.5 3 10V5l7-3z\"/><path d=\"M7.5 10l2 2 3.5-4\"/>",
  "binary": "<path d=\"M5 5h3v3H5zM12 5h3v3h-3zM5 12h3v3H5zM12 12h3v3h-3z\"/>",
  "cipher": "<rect x=\"3\" y=\"3\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"11\" y=\"3\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"3\" y=\"11\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"11\" y=\"11\" width=\"6\" height=\"6\" rx=\"1\"/><path d=\"M6 6l8 8M14 6L6 14\"/>",
  "control": "<circle cx=\"5\" cy=\"5\" r=\"2\"/><circle cx=\"15\" cy=\"5\" r=\"2\"/><circle cx=\"10\" cy=\"15\" r=\"2\"/><path d=\"M5 7v3c0 2 2 3 5 3s5-1 5-3V7\"/>",
  "digest": "<path d=\"M3.5 5h7M3.5 9h5M3.5 13h6\"/><path d=\"M13 3.5v13M16.5 5v11.5\"/><path d=\"M11.5 7h6.5M11.5 11h6.5\"/>",
  "directory": "<circle cx=\"7\" cy=\"7\" r=\"2.2\"/><circle cx=\"13.5\" cy=\"7.5\" r=\"1.8\"/><path d=\"M3.5 15c.6-2.4 2.2-3.5 3.5-3.5s2.9 1.1 3.5 3.5\"/><path d=\"M11.2 14.5c.4-1.6 1.5-2.4 2.3-2.4s1.9.8 2.3 2.4\"/>",
  "encoding": "<path d=\"M4 7h5l2 2h5M4 13h5l2-2h5\"/><path d=\"M14 5l3 3-3 3M6 15l-3-3 3-3\"/>",
  "essentials": "<circle cx=\"7\" cy=\"6.5\" r=\"2.3\"/><path d=\"M4 14.5c.5-2.3 2-3.4 3-3.4s2.5 1.1 3 3.4\"/><path d=\"M11.5 9.5l2.2 2.2 4-4\"/>",
  "fingerprint": "<path d=\"M10 17.5c0-4.2 2.8-6 2.8-9.2a2.8 2.8 0 10-5.6 0c0 1.1.35 2.1.9 3\"/><path d=\"M7.2 17c0-3.4 2.2-4.8 2.2-8\"/><path d=\"M12.8 17c0-3-1-4.4-1-7\"/><path d=\"M8.6 17.2c0-2.2 1.1-3.2 1.1-5.2\"/>",
  "flow": "<path d=\"M4 4v5h5\"/><path d=\"M4 9l5-5\"/><path d=\"M11 11v5h5\"/><path d=\"M11 16l5-5\"/>",
  "gear": "<circle cx=\"10\" cy=\"10\" r=\"2.2\"/><path d=\"M10 3.2v1.8M10 15v1.8M3.2 10h1.8M15 10h1.8M5.1 5.1l1.3 1.3M13.6 13.6l1.3 1.3M5.1 14.9l1.3-1.3M13.6 6.4l1.3-1.3\"/>",
  "hkp": "<circle cx=\"10\" cy=\"10\" r=\"3\"/><path d=\"M10 3v2M10 15v2M3 10h2M15 10h2M5.2 5.2l1.4 1.4M13.4 13.4l1.4 1.4M5.2 14.8l1.4-1.4M13.4 6.6l1.4-1.4\"/>",
  "io": "<rect x=\"3\" y=\"4\" width=\"14\" height=\"12\" rx=\"1.5\"/><path d=\"M3 8h14M7 12h6\"/>",
  "kdf": "<path d=\"M3.5 3h13L12 9H8L3.5 3z\"/><path d=\"M8 9h4v2.2\"/><path d=\"M6 11.2h8L12.5 17h-5L6 11.2z\"/>",
  "keys": "<path d=\"M8 11a3 3 0 113.2-2.8L16 13v2h-2v2h-2v-2h-1.5z\"/><circle cx=\"7.5\" cy=\"8\" r=\"1\"/>",
  "lock": "<rect x=\"3.5\" y=\"9\" width=\"13\" height=\"9\" rx=\"1.5\"/><path d=\"M6.5 9V6.5a3.5 3.5 0 017 0V9\"/><path d=\"M10 12v3\"/>",
  "more": "<circle cx=\"5\" cy=\"10\" r=\"1.3\"/><circle cx=\"10\" cy=\"10\" r=\"1.3\"/><circle cx=\"15\" cy=\"10\" r=\"1.3\"/>",
  "openpgp": "<rect x=\"3\" y=\"8\" width=\"14\" height=\"10\" rx=\"1.5\"/><path d=\"M3 9.5l7 4.5 7-4.5\"/><path d=\"M7 8V6.5a3 3 0 016 0V8\"/>",
  "password": "<circle cx=\"7\" cy=\"10\" r=\"2.5\"/><path d=\"M9.2 10H17v2.5h-2V15h-2v-2.5H11\"/>",
  "ports": "<path d=\"M4 7h5v6H4zM11 7h5v6h-5z\"/><path d=\"M9 10h2\"/>",
  "pubkey": "<path d=\"M3 9.5l7 4.5 7-4.5\"/><rect x=\"3\" y=\"8\" width=\"14\" height=\"9\" rx=\"1\"/><circle cx=\"10\" cy=\"5\" r=\"2\"/>",
  "recipients": "<circle cx=\"7\" cy=\"7\" r=\"2.2\"/><circle cx=\"13.5\" cy=\"7.5\" r=\"1.8\"/><path d=\"M3.5 15c.6-2.4 2.2-3.5 3.5-3.5s2.9 1.1 3.5 3.5\"/><path d=\"M11.2 14.5c.4-1.6 1.5-2.4 2.3-2.4s1.9.8 2.3 2.4\"/>",
  "recover": "<path d=\"M4 10h5l2-3 2 6 2-3h5\"/><path d=\"M16 6v4h4\"/>",
  "rsa": "<rect x=\"3.5\" y=\"3\" width=\"10\" height=\"14\" rx=\"1\"/><path d=\"M6 7h5M6 10h5M6 13h3\"/><circle cx=\"15\" cy=\"12\" r=\"2\"/><path d=\"M15 14v2.5h1.2\"/>",
  "shortcuts": "<rect x=\"3\" y=\"5\" width=\"14\" height=\"11\" rx=\"1.5\"/><path d=\"M6 9h2M9.5 9h2M13 9h1M6 12h8\"/>",
  "sign": "<path d=\"M4 16c2-4 5-7 8-8l3-3 2 2-3 3c-1 3-4 6-8 8z\"/>",
  "split": "<path d=\"M8 4l-4 6h4l-3 6M12 4l4 6h-4l3 6\"/>",
  "sss": "<rect x=\"3.5\" y=\"6\" width=\"9\" height=\"11\" rx=\"1\"/><rect x=\"6\" y=\"4\" width=\"9\" height=\"11\" rx=\"1\"/><rect x=\"8.5\" y=\"2\" width=\"9\" height=\"11\" rx=\"1\"/>",
  "text": "<path d=\"M5 5h10M7 5v10M5 15h4M11 9h4M11 12h3\"/>",
  "unlock": "<rect x=\"3.5\" y=\"9\" width=\"13\" height=\"9\" rx=\"1.5\"/><path d=\"M6.5 9V6.5a3.5 3.5 0 017 0V5\"/><path d=\"M10 12v3\"/>",
  "variables": "<rect x=\"3.5\" y=\"4\" width=\"5\" height=\"5\" rx=\"1\"/><rect x=\"11.5\" y=\"4\" width=\"5\" height=\"5\" rx=\"1\"/><rect x=\"3.5\" y=\"11\" width=\"5\" height=\"5\" rx=\"1\"/><path d=\"M12.5 13.5h4M14.5 11.5v4\"/>",
  "webauthn": "<circle cx=\"6.8\" cy=\"6.5\" r=\"2.4\"/><path d=\"M3.6 15c.6-2.6 2.2-3.8 3.2-3.8s2.6 1.2 3.2 3.8\"/><path d=\"M11.2 10.2a2.2 2.2 0 112.4-2.1L16.5 12v1.3h-1.3V15H13.8v-1.7h-1.3z\"/><circle cx=\"11\" cy=\"8.2\" r=\"0.7\"/>",
  "webcrypto": "<rect x=\"3\" y=\"3.5\" width=\"14\" height=\"13\" rx=\"1.5\"/><path d=\"M3 7h14\"/><circle cx=\"9.5\" cy=\"12.2\" r=\"2\"/><path d=\"M11.3 12.2H16v1.4h-1.3V16H13.3v-2.4h-1.2z\"/>",
  "wrap": "<path d=\"M3 8l7-4 7 4v8l-7 4-7-4V8z\"/><path d=\"M3 8l7 4 7-4M10 12v8\"/>",
};

/**
 * @param {string|undefined|null} id
 * @param {string} [className]
 * @returns {string}
 */
export function glyphHtml(id, className = "ops-glyph") {
  const key = String(id || "");
  const inner = GLYPH_PATHS[key];
  if (!inner) return "";
  return `<svg class="${className}" width="16" height="16" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${inner}</svg>`;
}
