name: marketplace

on:
  push:
    paths:
      - marketplace/**
      - infra/**
  pull_request:
    paths:
      - marketplace/**
      - infra/**

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - run: bash scripts/package-marketplace.sh
      - run: az bicep build --file marketplace/mainTemplate.bicep
